// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByWs19KnOqRzdOVd8rtfr8fcD3OoLpTLU',
    appId: '1:565471500049:web:c75e43e14a3fb3d6b29eb0',
    messagingSenderId: '565471500049',
    projectId: 'g4c-8854b',
    authDomain: 'g4c-8854b.firebaseapp.com',
    storageBucket: 'g4c-8854b.appspot.com',
    measurementId: 'G-MLHY37F2FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCisNRuuA4E6I3-dUAxT1L2iwjUvKuJOho',
    appId: '1:565471500049:android:8b0209d7c58541cab29eb0',
    messagingSenderId: '565471500049',
    projectId: 'g4c-8854b',
    storageBucket: 'g4c-8854b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWV7DnBgoNS40YYY1bw8ot76tsLVMvCBM',
    appId: '1:565471500049:ios:0b2302f6eb2211c0b29eb0',
    messagingSenderId: '565471500049',
    projectId: 'g4c-8854b',
    storageBucket: 'g4c-8854b.appspot.com',
    androidClientId: '565471500049-ck71cefma33bsomchu0ct46qht11lm1v.apps.googleusercontent.com',
    iosClientId: '565471500049-1pqql9tcjvt7gfubjppcc32mlj1j62l5.apps.googleusercontent.com',
    iosBundleId: 'com.example.g4c',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWV7DnBgoNS40YYY1bw8ot76tsLVMvCBM',
    appId: '1:565471500049:ios:16fa9fb5ee124cddb29eb0',
    messagingSenderId: '565471500049',
    projectId: 'g4c-8854b',
    storageBucket: 'g4c-8854b.appspot.com',
    androidClientId: '565471500049-ck71cefma33bsomchu0ct46qht11lm1v.apps.googleusercontent.com',
    iosClientId: '565471500049-l3aignviapdvs067shhhiqa36a92a8un.apps.googleusercontent.com',
    iosBundleId: 'com.example.g4c.RunnerTests',
  );
}
